library(dplyr)
head(mtcars)
filter(mtcars,mpg>20,cyl==6)
head(arrange(mtcars,cyl,desc(wt)))
head(arrange(mtcars,cyl,-wt))
head(select(mtcars,mpg,hp))
distinct(mtcars,gear)
head(mutate(mtcars,performance=hp/wt))
summarize(mtcars,mean(mpg))
mtcars %>% filter(cyl ==6) %>% summarize(mean(hp))
